### ISSUE TITLE
Have you used this approach on live projects? Would love to hear how it worked out

### ISSUE THREAD

**Issue by paulgrieselhuber** [peaonunes/apollo-multiple-clients-example#1]
I am working on scaffolding out a project with the need for multiple providers, and trying to avoid creating a Gateway API. The example project here looks promising. Just curious if you ended up going in this direction, and how successful it has been if so.

**Comment by peaonunes** [comment]
Hi, @paulisloud , I am surviving running this approach. However, I just need to make use of one the second client in very few isolated components, I guess they are isolated enough.

I think that might be a must have condition when going for this approach, isolate the workaround to not spread too much on your code where you might end up mixing up clients, queries and making the code not reliable.

One guy come to me with a package with a proposal to handle multiple provides and come out with this repo (https://github.com/titel-media/react-apollo-multiple-client) based on what I have posted.
I think it might be a valid way for you doing it and might make your code more maintainable, I haven't had time to test though.

**Comment by paulgrieselhuber** [comment]
Thanks for the quick feedback. And glad to hear that it sounds like the primary things that you've run in to have been code organization related, vs. high-impact, stomach-dropping Apollo cache issues or something similar.

Interestingly enough I was playing with that package earlier, but got further with yours. I think the documentation in yours, plus being able to clone and run helped a lot. May throw his on top of the little graphql servers in your project and see what happens.

**Comment by peaonunes** [comment]
Nice! Let the maintainers of the `react-apollo-multiple-client` know if you run into any issues or if you have any feedback for them. This will help the package to evolve and gain relevance.

**Comment by paulgrieselhuber** [comment]
Just realized I had an open issue on this project here. Dropping a link to your post on medium: https://medium.com/open-graphql/apollo-multiple-clients-with-react-b34b571210a5. Conversation between @peaonunes and I goes in to some depth on this subject.
